### ISSUE TITLE
unable to build due to missing assembly Com.Tubb.Smrv

### ISSUE THREAD

**Issue by koo9** [yufeih/Xamarin.RecyclerView.SwipeMenu#1]
it's not in the nudget config, where to download this dll?

**Comment by yufeih** [comment]
It is build from [this](https://github.com/yufeih/Xamarin.RecyclerView.SwipeMenu/blob/master/Xamarin.RecyclerView.SwipeMenu/Xamarin.RecyclerView.SwipeMenu.csproj) xamarin binding project. You should build that project
